openapi: 3.2.0
info:
  version: '2022-08-01'
  title: SMS Messaging Phone Numbers API
  description: Phone Numbers
servers: []
tags:
- name: phone_numbers
  description: Phone Numbers
paths:
  /phone_numbers:
    get:
      summary: Gets summarized metadata for phone numbers assigned to an Invoca Network
      responses:
        '200':
          content:
            application/json:
              example:
                phone_numbers:
                - phone_number: '+18885550100'
                  created_at: '2022-01-31T23:49:03.316Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
                - phone_number: '+18885550100'
                  created_at: '2022-01-31T23:49:04.316Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
                - phone_number: '+18885550100'
                  created_at: '2022-01-31T23:49:05.316Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
                - phone_number: '+18885550100'
                  created_at: '2022-01-31T23:49:06.316Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
                - phone_number: '+18885550100'
                  created_at: '2022-01-31T23:49:07.316Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
                pagination:
                  prev_url: /sms/2022-08-01/phone_numbers?page=
                  series:
                  - '1'
                  - 2
                  in: 5
                  scaffold_url: /sms/2022-08-01/phone_numbers?page=__pagy_page__
                  from: 1
                  last_url: /sms/2022-08-01/phone_numbers?page=2
                  pages: 2
                  count: 7
                  last: 2
                  first_url: /sms/2022-08-01/phone_numbers?page=1
                  items: 5
                  next: 2
                  next_url: /sms/2022-08-01/phone_numbers?page=2
                  to: 5
                  prev: null
                  page: 1
                  page_url: /sms/2022-08-01/phone_numbers?page=1
              schema:
                type: object
                properties:
                  phone_numbers:
                    items:
                      type: object
                      properties:
                        phone_number:
                          type: string
                        created_at:
                          type: string
                        deleted_at: {}
                        carrier_interface:
                          type: string
                        enabled_at: {}
                    type: array
                  pagination:
                    type: object
                    properties:
                      prev_url:
                        type: string
                      series:
                        items:
                          type: string
                        type: array
                      in:
                        type: integer
                      scaffold_url:
                        type: string
                      from:
                        type: integer
                      last_url:
                        type: string
                      pages:
                        type: integer
                      count:
                        type: integer
                      last:
                        type: integer
                      first_url:
                        type: string
                      items:
                        type: integer
                      next:
                        type: integer
                      next_url:
                        type: string
                      to:
                        type: integer
                      prev: {}
                      page:
                        type: integer
                      page_url:
                        type: string
          description: get the first page of paginated phone numbers
      tags:
      - phone_numbers
  /phone_numbers/{phone_number}:
    delete:
      summary: Deletes a phone number from SMS Messaging
      responses:
        '200':
          content:
            application/json:
              example:
                phone_number:
                  phone_number: '+18885550100'
                  virtual_line_id: 200
                  network_id: 12345
                  created_at: '2022-03-14T20:30:12.000Z'
                  deleted_at: '2022-04-14T20:30:12.000Z'
                  carrier_interface: bandwidth
                  enabled_at: null
              schema:
                type: object
                properties:
                  phone_number:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      virtual_line_id:
                        type: integer
                      network_id:
                        type: integer
                      created_at:
                        type: string
                      deleted_at:
                        type: string
                      carrier_interface:
                        type: string
                      enabled_at: {}
          description: is expected to eq {"phone_number"=>{"carrier_interface"=>"bandwidth", "created_at"=>"2022-03-14T20:30:12.000Z", "delete...Z", "enabled_at"=>nil, "network_id"=>12345, "phone_number"=>"+18885550100", "virtual_line_id"=>200}}
        '404':
          content:
            application/json:
              example:
                message: Not Found - the requested phone number, +18885550100, is not in the system
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be not found
        '403':
          content:
            application/json:
              example:
                message: Forbidden
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be forbidden
        '422':
          content:
            application/json:
              example:
                message: Unprocessable Entity - the requested phone number is not valid
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be unprocessable
      parameters:
      - $ref: '#/components/parameters/phone_number'
      tags:
      - phone_numbers
    get:
      summary: Gets detailed phone number SMS Messaging metadata
      responses:
        '200':
          content:
            application/json:
              example:
                phone_number:
                  phone_number: '+18885550100'
                  virtual_line_id: 197
                  network_id: 12345
                  created_at: '2022-03-14T20:30:12.000Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: null
              schema:
                type: object
                properties:
                  phone_number:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      virtual_line_id:
                        type: integer
                      network_id:
                        type: integer
                      created_at:
                        type: string
                      deleted_at: {}
                      carrier_interface:
                        type: string
                      enabled_at: {}
          description: is expected to eq {"phone_number"=>{"carrier_interface"=>"bandwidth", "created_at"=>"2022-03-14T20:30:12.000Z", "delete...il, "enabled_at"=>nil, "network_id"=>12345, "phone_number"=>"+18885550100", "virtual_line_id"=>197}}
        '404':
          content:
            application/json:
              example:
                message: Not Found - the requested phone number, +18885550100, is not in the system
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be not found
        '403':
          content:
            application/json:
              example:
                message: Forbidden
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be forbidden
        '422':
          content:
            application/json:
              example:
                message: Unprocessable Entity - the requested phone number is not valid
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be unprocessable
      parameters:
      - $ref: '#/components/parameters/phone_number'
      tags:
      - phone_numbers
    post:
      summary: Adds a phone number to involve with SMS Messaging
      responses:
        '201':
          content:
            application/json:
              example:
                phone_number:
                  phone_number: '+18885550100'
                  virtual_line_id: 67890
                  network_id: 12345
                  created_at: '2022-03-14T20:30:12.000Z'
                  deleted_at: null
                  carrier_interface: bandwidth
                  enabled_at: '2022-03-14T20:30:12.000Z'
              schema:
                type: object
                properties:
                  phone_number:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      virtual_line_id:
                        type: integer
                      network_id:
                        type: integer
                      created_at:
                        type: string
                      deleted_at: {}
                      carrier_interface:
                        type: string
                      enabled_at:
                        type:
                        - string
                        - 'null'
          description: is expected to eq "https://example.org/sms/2022-08-01/phone_numbers/+18885550100"
        '422':
          content:
            application/json:
              example:
                message: Unprocessable Entity - the requested phone number is not valid
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be unprocessable
        '403':
          content:
            application/json:
              example:
                message: Forbidden
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: is expected to be forbidden
        '204':
          content:
            ? ''
            : example: ''
              schema:
                type: string
          description: is expected to eq "https://example.org/sms/2022-08-01/phone_numbers/+18885550100"
        '409':
          content:
            application/json:
              example: {}
              schema:
                type: object
                properties: {}
          description: is expected to be conflict
      parameters:
      - $ref: '#/components/parameters/phone_number'
      tags:
      - phone_numbers
components:
  parameters:
    phone_number:
      schema:
        type: string
      description: The Phone Number in E.164 Format
      in: path
      required: true
      example: '+18885550100'
      name: phone_number
